### ISSUE TITLE
Sklearn breaks classification model 

### ISSUE THREAD

**Issue by angerhang** [activityMonitoring/biobankAccelerometerAnalysis#101]
As mentioned in https://github.com/activityMonitoring/biobankAccelerometerAnalysis/pull/99, sklearn 0.24 breaks forest. When one imports the ``_forest`` package, the current downloaded model is not compatible with the newly imported model for classification. 

Ideally, we perhaps should retrain the model with the right class and use sklearn as the latest supported version.

**Comment by R-Walmsley** [comment]
Addressed in PR #108.
