### ISSUE TITLE
FutureWarning: keyword arguments in sklearn functions

### ISSUE THREAD

**Issue by R-Walmsley** [activityMonitoring/biobankAccelerometerAnalysis#119]
@smallsr noticed a FutureWarning on some sklearn functions that in versions from 0.25/1.0 forwards arguments should be specified as keyword rather than positional arguments. This is a fairly straightforward fix, and probably worth anticipating. 

https://scikit-learn.org/stable/whats_new/v0.23.html#enforcing-keyword-only-arguments

**Comment by chanshing** [comment]
Is this still an issue after c14c1a35a4a2b4a2dc5a8ceae592a87e2438bff2 ?
