### ISSUE TITLE
Installation instructions clarification

### ISSUE THREAD

**Issue by smallsr** [activityMonitoring/biobankAccelerometerAnalysis#128]
For users following the installation code exactly as laid out in the instructions, an error will be generated after line 2, as the instructions do not point to changing directory into the new biobankAccelerometerAnalysis directory before running utilities/downloadDataModels.sh. It might be helpful for the command-line-timid user to have that extra line in for a smoother copy-paste installation. 
$ git clone git@github.com:activityMonitoring/biobankAccelerometerAnalysis.git
**$ bash cd ./biobankAccelerometerAnalysis**   (or conversely, just amending the second line to $bash ./biobankAccelerometerAnalysis/utilities/downloadDataModels.sh)
$ bash utilities/downloadDataModels.sh
$ pip install --upgrade pip
$ pip3 install --upgrade -r requirements.txt # Installs a known working set of dependencies, other package versions may also work.
$ javac -cp java/JTransforms-3.1-with-dependencies.jar java/*.java

**Comment by angerhang** [comment]
Well spotted! Yap this should have be changed per your suggestions.
Thx Scot.
