### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mobatusi** [activityMonitoring/biobankAccelerometerAnalysis#133]
Please add cd biobankAccelerometerAnalysis in the installation instructions after "git clone git@github.com:activityMonitoring/biobankAccelerometerAnalysis.git" Otherwise the person following the instructions may not be aware that this step to be in the biobankAccelerometerAnalysis directory to run the following step of "bash utilities/downloadDataModels.sh" Thank you!

**Comment by angerhang** [comment]
Thanks for reporting @mobatusi . This looks like a duplicate of https://github.com/activityMonitoring/biobankAccelerometerAnalysis/issues/128 and a PR has already been submitted, thus closing.
