### ISSUE TITLE
Imputation output consistency

### ISSUE THREAD

**Issue by angerhang** [activityMonitoring/biobankAccelerometerAnalysis#134]
So apparently, when imputation is being done, the the hand-crafted output will be imputed but the raw files wouldn't. This is a bit ambiguous because one could agree that the raw files, `*.npy` and `*.csv.gz` should contain the imputed raw data too.

Good to keep all of them consistent w.r.t. imputation I suppose?
Thoughts? @chanshing  @R-Walmsley @aidendoherty

**Comment by chanshing** [comment]
Hi Hang. This has been changed. Now we don't impute neither raw nor feature frames (but for the feature frames we do set them to NaN if nonwear). Now we only temporarily impute to compute the final summary statistics. It's a bit involved but here it is:

https://github.com/activityMonitoring/biobankAccelerometerAnalysis/blob/d984a0bed26f6d80f2bf30df42556e284480c4e8/accelerometer/summarisation.py#L227-L272
