### ISSUE TITLE
requirements.txt may need updating 

### ISSUE THREAD

**Issue by Tim-Yu** [activityMonitoring/biobankAccelerometerAnalysis#15]
According to me and other fellows experience, only by installing all the packages without assigning the specific version listed in the requirements.txt can make sure the code runs properly, which may indicate that some newer version of packages in requirements should be used to allow the programme to be functional.

**Comment by aidendoherty** [comment]
Thanks for noting this. Our new major update instead uses a pip install to handle dependencies (see README page + new readTheDocs supporting documentation)
