### ISSUE TITLE
Plot with label

### ISSUE THREAD

**Issue by angerhang** [activityMonitoring/biobankAccelerometerAnalysis#190]
From @chanshing 

> 
    To help with the plot interpretations we should probably use hardcoded min-max range for the trace plot. I think [0, 2.5] should work for 99% of cases. Accel values above 2.5 are very rate. 

> 
    Currently it's normalized by the in-data min-max. So even a full day of sleep the trace plot would look noisy, but the range is tiny

**Comment by chanshing** [comment]
Done! bb7dfde5daceaa9dbe0cc2ecb402fee56c5f1145
