### ISSUE TITLE
Provide an option to disable imputation

### ISSUE THREAD

**Issue by JianWang2016** [activityMonitoring/biobankAccelerometerAnalysis#22]
Though it is highly recommended to impute non-wear, it may be necessary to examine and compare non-imputed with imputed to get a feel of the impact of imputation.

setting '-nonWearThreshold -1' in commit [110c118](https://github.com/activityMonitoring/biobankAccelerometerAnalysis/commit/110c118e936a28af65d888e0877e4f388512124d) by @supersational was not merged.  

Perhaps to include a [toggle](https://github.com/activityMonitoring/biobankAccelerometerAnalysis/blob/master/accelerometer/summariseEpoch.py#L432) with a suitable cautious/danger-laden name to highlight that it should be used with care.

**Comment by aidendoherty** [comment]
Now fixed in commit [6948716](https://github.com/activityMonitoring/biobankAccelerometerAnalysis/commit/6948716c933bd7a4d5a6e9be6626622c9318511e)

It is highly recommended to not change this flag. This functionality can now be achieved by toggling the --useRecommendedImputation flag
