### ISSUE TITLE
--useRecommendedImputation False doesn't appear working

### ISSUE THREAD

**Issue by JianWang2016** [activityMonitoring/biobankAccelerometerAnalysis#40]
Thanks much for enabling  to set --useRecommendedImputation False.  I tried it and could see in the stdout file that it indeed has "useRecommendedImputation : False".  However, when I examined the plot, there is still regions in yellow as imputed.  In the timeSeries csv file, I can see rows with imputed = 1 as if the imputation was carried out as usual.  Any advice?

**Comment by aidendoherty** [comment]
Thanks @JianWang2016 

Option --useRecommendedImputation has now been added to accPlot.py (see 99bfcf6e540e88daf2d79065b9304f4fcffa900c)
