### ISSUE TITLE
showing yaxis tick labels

### ISSUE THREAD

**Issue by xiangnandang** [activityMonitoring/biobankAccelerometerAnalysis#50]
there could be potential benefit by showing yaxis tick labels:

1. making sure it's visibly displayed that all days' individual plots are sharing same ylim. This piece of information might feel "common sense" for many people here, but could be confusing to outsiders or new users.

1. Knowing the numbers could also give a quick overview about this particular participant's overall activity level

for example:
![image](https://user-images.githubusercontent.com/36307794/83801572-5ecc7c80-a677-11ea-882a-2c9facff61c3.png)

**Comment by R-Walmsley** [comment]
Hi @xiangnandang, 

Thank you very much for this suggestion! We discussed it yesterday and thought that this feature would sometimes be useful (as you describe), but would make the plots visually quite a lot more complex. We therefore decided against implementing it in general. More than happy to discuss this further (and also of course feel free to submit a PR with your suggested version...)
