### ISSUE TITLE
gui.py not running in Linux

### ISSUE THREAD

**Issue by aidendoherty** [activityMonitoring/biobankAccelerometerAnalysis#6]
cmd > python gui.py 

output:
Traceback (most recent call last):
  File "gui.py", line 485, in <module>
    TkinterGUI(root).pack()
  File "gui.py", line 153, in **init**
    self.advancedOptionInputs.append({'frame':frame, 'pack_opts': frame.pack_info()})
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1900, in pack_info
    self.tk.call('pack', 'info', self._w))
TypeError: coercing to Unicode: need string or buffer, _tkinter.Tcl_Obj found

**Comment by aidendoherty** [comment]
My linux version of python is: Python 2.7.6

**Comment by supersational** [comment]
Which linux distro is that on?

**Comment by aidendoherty** [comment]
Lubuntu/Ubuntu 14.04.3 LTS

**Comment by supersational** [comment]
![image](https://cloud.githubusercontent.com/assets/11251397/12720164/36c51232-c8f1-11e5-9e5e-f6f1e8ab3ea9.png)
Works for me with a fresh install of Ubuntu/Anaconda (2.7.6), are you using the standard python installation?

**Comment by aidendoherty** [comment]
We no longer actively support GUI's.
